<Project>
    <PropertyGroup>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
        <OutputPath>$(MSBuildThisFileDirectory)bin/$(Configuration)/$(MSBuildProjectName)/$(TargetFramework)/</OutputPath>
    </PropertyGroup>
</Project>