namespace Ragent;

public enum EModel {
    OLLAMA_MISTRAL,
    OLLAMA_LLAMA32,
    GEMINI_2_5_FLASH,
    OPENAI_GPT_4O,
    OPENAI_GPT_4O_MINI,
    ANTHROPIC_CLAUDE_SONNET_4_5,
    ANTHROPIC_CLAUDE_HAIKU_4_5,
}